crud/urls.py
from django.conf.urls import patterns, url
from crud import views

urlpatterns = patterns('',
  url(r'^$', views.ServerList.as_view(), name='server_list'),
  url(r'^new$', views.ServerCreate.as_view(), name='server_new'),
  url(r'^edit/(?P<pk>\d+)$', views.ServerUpdate.as_view(), name='server_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.ServerDelete.as_view(), name='server_delete'),
)

ecom/urls.py
from django.conf.urls import patterns, url

from ecom import views

urlpatterns = patterns('',
  url(r'^$', views.ecom_list, name='ecom_list'),
  url(r'^new$', views.ecom_create, name='ecom_create'),
  url(r'^edit/(?P<pk>\d+)$', views.ecom_update, name='ecom_update'),
  url(r'^delete/(?P<pk>\d+)$', views.ecom_delete, name='ecom_delete'),
)

mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls')),
    url(r'^server/', include('crud.urls')),
    url(r'^ecom/', include('ecom.urls')),
]

polls/urls.py
from django.conf.urls import url

from .import views

app_name = 'polls'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^(?P<question_id>[0-9]+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<question_id>[0-9]+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
    ]

crud/models.py
from __future__ import unicode_literals
from django.db import models
from django.core.urlresolvers import reverse

class Server(models.Model):
    name = models.CharField(max_length=200)
    ip = models.GenericIPAddressField()
    order = models.IntegerField()

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('server_edit', kwargs={'pk': self.pk})

ecom/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.
class ProdTable(models.Model):
    pname = models.CharField(max_length=200)
    pamount = models.FloatField(default=0)

    def __str__(self):
        return self.pname, self.pamount

polls/models.py
from __future__ import unicode_literals

from django.db import models

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):
        return self.choice_text

crud/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy

from crud.models import Server

class ServerList(ListView):
    model = Server

class ServerCreate(CreateView):
    model = Server
    success_url = reverse_lazy('server_list')
    fields = ['name', 'ip', 'order']

class ServerUpdate(UpdateView):
    model = Server
    success_url = reverse_lazy('server_list')
    fields = ['name', 'ip', 'order']

class ServerDelete(DeleteView):
    model = Server
    success_url = reverse_lazy('server_list')

ecom/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from ecom.models import ProdTable
# Create your views here.

class ecomForm(ModelForm):
    class Meta:
        model = ProdTable
        fields = ['pname','pamount']

def ecom_list(request, template_name='ecom/ecom_list.html'):
    ecomsProducts = ProdTable.objects.all()
    data = {}
    data['object_list'] = ecomsProducts
    return render(request, template_name, data)

def ecom_create(request, template_name='ecom/ecom_form.html'):
    form = ecomForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('ecom_list')
    return render(request, template_name, {'form':form})

def ecom_update(request, pk, template_name='ecom/ecom_form.html'):
    ecomUpdate = get_object_or_404(ProdTable, pk=pk)
    form = ecomForm(request.POST or None, instance=ecomUpdate)
    if form.is_valid():
        form.save()
        return redirect('ecom_list')
    return render(request, template_name, {'form':form})

def ecom_delete(request, pk, template_name='ecom/ecom_confirm_delete.html'):
    ecomDelete = get_object_or_404(ProdTable, pk=pk)    
    if request.method=='POST':
        server.delete()
        return redirect('ecom_list')
    return render(request, template_name, {'object':ecomDelete})

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import Question

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})

def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)

crud/templates/crud/server_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

crud/templates/crud/server_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

crud/templates/crud/server_list.html
<h1>Servers</h1>
<ul>
    {% for server in object_list %}
    <li>{{ server.name }}  :  
    <a href="{% url "server_edit" server.id %}">{{ server.ip }}</a>
    <a href="{% url "server_delete" server.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url "server_new" %}">New</a>

ecom/templates/ecom/ecom_confirm.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

ecom/templates/ecom/ecom_confirm_delete.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

ecom/templates/ecom/ecom_form.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

ecom/templates/ecom/ecom_list.html
<h1>Products</h1>
<ul>
    {% for e in object_list %}
    <li>{{ e.pname }}  :  
    <a href="{% url "ecom_update" e.id %}">edit</a>
    <a href="{% url "ecom_delete" e.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url "ecom_create" %}">New</a>

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}